// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpq32PEt7Kp8PoahQlLWL2HL3Yei04O5Q',
    appId: '1:852541175665:android:117ae0029fe2c822d728d0',
    messagingSenderId: '852541175665',
    projectId: 'ecoroute-4eeb1',
    databaseURL: 'https://ecoroute-4eeb1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ecoroute-4eeb1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlT3mfcNkVbln9bxnzsRlNTle2GtNgtJw',
    appId: '1:852541175665:ios:e5eda080fc51d2bfd728d0',
    messagingSenderId: '852541175665',
    projectId: 'ecoroute-4eeb1',
    databaseURL: 'https://ecoroute-4eeb1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ecoroute-4eeb1.appspot.com',
    iosClientId: '852541175665-40pkg48jtftp999e8i5cb678fan0j4qn.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecoRouteSe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlT3mfcNkVbln9bxnzsRlNTle2GtNgtJw',
    appId: '1:852541175665:ios:49f5225f5e61ec05d728d0',
    messagingSenderId: '852541175665',
    projectId: 'ecoroute-4eeb1',
    databaseURL: 'https://ecoroute-4eeb1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ecoroute-4eeb1.appspot.com',
    iosClientId: '852541175665-apcp8jbl59t3d924rolecq6mjn890pru.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecoRouteSe.RunnerTests',
  );
}
